apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: cp-enriched-customer-behaviour
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 6
  kafkaRestClassRef:
    name: krc-cfk