apiVersion: apps/v1
kind: Deployment
metadata:
  name: propensity-service
  namespace: internal
  labels:
    app: propensity-service
spec:
  replicas: 6
  selector:
    matchLabels:
      app: propensity-service
  template:
    metadata:
      labels:
        app: propensity-service
    spec:
      containers:
      - name: propensity-score
        image: 829250931565.dkr.ecr.us-west-2.amazonaws.com/hsbc-ops-docker-registry:latest
        imagePullPolicy: Always
        command:
        - python
        - customer-activity-propensity-service.py
        env:
        - name: KAFKA_TOPIC
          value: aws-enriched-customer-behaviour-clone-0
        - name: SR_URL
          value: https://psrc-e0919.us-east-2.aws.confluent.cloud
        - name: VALUE_SR_ID
          value: '100104'
        - name: KEY_SR_ID
          value: '100030'
        - name: KINESIS_STREAM_NAME
          value: hsbc_customer_analytics_stream
        - name: AWS_REGION
          value: us-west-2
        - name: KAFKA_BOOTSTRAP_URL
          value: pkc-jn77q.us-west-2.aws.confluent.cloud:9092 
        - name: KAFKA_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: apps-secret
              key: KAFKA_SASL_USERNAME
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apps-secret
              key: KAFKA_SASL_PASSWORD
        - name: SR_AUTH
          valueFrom:
            secretKeyRef:
              name: apps-secret
              key: SR_AUTH
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1092Mi"
            cpu: "500m"
