apiVersion: batch/v1
kind: CronJob
metadata:
  name: customer-registration-service-cron
  namespace: internal
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: customer-registration
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: DB_PASS
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: DB_URI
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: DB_NAME
            - name: DB_PORT
              value: "5432"
            - name: ITERATION_COUNT
              value: "10"
            image: 829250931565.dkr.ecr.us-west-2.amazonaws.com/hsbc-ops-docker-registry:latest
            imagePullPolicy: Always
            command:
            - python
            - customer-registration-service.py
          restartPolicy: OnFailure
