apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: internal
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  selector:
    app: nginx-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: internal
data:
  nginx.conf: |
    worker_processes auto;

    events {
      worker_connections 1024;
    }

    stream {
      upstream postgresql_backend {
        server hsbc-ops-db.cndsjke6xo5r.us-west-2.rds.amazonaws.com:5432;
      }

      server {
        listen 5432;
        proxy_pass postgresql_backend;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: nginx
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: nginx-proxy-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: nginx-proxy-config
