apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::829250931565:role/hsbc-ops-node-group
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      - eks-console-dashboard-full-access-group
      - system:discovery
      - system:nodes
      userarn: arn:aws:iam::829250931565:federated-user/AWSReservedSSO_nonprod-administrator_ff555b249eb304bc/sdubey@confluent.io
      username: AWSReservedSSO_nonprod-administrator_ff555b249eb304bc/sdubey@confluent.io
    - groups:
      - system:masters
      - eks-console-dashboard-full-access-group
      - system:discovery
      - system:nodes
      userarn: arn:aws:iam::829250931565:user/checkride-team-4-terraform
      username: checkride-team-4-terraform

